apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
        app.kubernetes.io/name: hola
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: holaweb
        app.kubernetes.io/version: 0.0.4
        app.kubernetes.io/build-version: "1"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3333'
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
        - name: hola
          image: mnroman/hello-world-nodejs:0.0.4
          ports:
            - containerPort: 3333
          env:
          - name: DT_CUSTOM_PROP
            value: "version=0.0.4 keptn_project=dynatrace keptn_service=holaweb keptn_stage=quality-stage"
          - name: "DT_RELEASE_VERSION"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/version']
          - name: "DT_RELEASE_PRODUCT"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/part-of']
          - name: "DT_BUILD_VERSION"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/build-version']

          imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
