apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: holaweb-metrics
  namespace: hola-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: hola
  namespaceSelector:
    matchNames:
    - hola-app
  endpoints:
  - port: frontend
