apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: holaweb-metrics
  namespace: prometheus
  labels:
    release: pc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: hola
  namespaceSelector:
    matchNames:
    - hola-app
  endpoints:
  - port: frontend