apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola
  template:
    metadata:
      labels:
        app: hola
        app.kubernetes.io/name: hola
        app.kubernetes.io/instance: "{{ .Values.keptn.service }}"
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: holaweb
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3333'
    spec:
      containers:
        - name: hola
          image: mnroman/hello-world-nodejs:0.0.1
          ports:
            - containerPort: 3333
          imagePullPolicy: Always
          env:
          - name: "DT_RELEASE_VERSION"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/version']
          - name: "DT_RELEASE_PRODUCT"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/part-of']
      imagePullSecrets:
      - name: regcred
