name: Build, Push Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        working-directory: ./src
        run: npm install

      # 4️⃣ Build proyecto
      - name: Build project
        working-directory: ./src
        run: npm run build --if-present

      # 5️⃣ Generar versión automática basada en commits
      - name: Generate build version
        id: version
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "BUILD_VERSION=1.0.$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Build version: $BUILD_VERSION"

      # 6️⃣ Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ Construir y push de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mitienda:${{ env.BUILD_VERSION }}

      # 8️⃣ Actualizar Deployment de Kubernetes
      - name: Update Kubernetes deployment
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
        run: |
          kubectl set image deployment/mitienda \
            mitienda=${{ secrets.DOCKERHUB_USERNAME }}/mitienda:$BUILD_VERSION --record
          
          # Opcional: actualizar la label buildVersion en el Deployment
          kubectl patch deployment mitienda \
            -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"buildVersion\":\"$BUILD_VERSION\"}}}}}"
